const steps = [
  {key:'details', title:'Which vehicle are we documenting?', intro:'Start with the details that identify this vehicle.'},
  {key:'transport', title:'Where is it going?', intro:'Add the planned collection details. You can update these before finishing.'},
  {key:'front', title:'Photograph the front', intro:'Stand directly in front. Include the whole front of the vehicle.'},
  {key:'front_left', title:'Front-left angle', intro:'Show the front and the driver side together.'},
  {key:'driver_side', title:'Driver side', intro:'Step back so the full side is visible.'},
  {key:'rear_left', title:'Rear-left angle', intro:'Show the rear and driver side together.'},
  {key:'rear', title:'Photograph the rear', intro:'Include the entire rear of the vehicle.'},
  {key:'rear_right', title:'Rear-right angle', intro:'Show the rear and passenger side together.'},
  {key:'passenger_side', title:'Passenger side', intro:'Step back so the full side is visible.'},
  {key:'front_right', title:'Front-right angle', intro:'Show the front and passenger side together.'},
  {key:'details_photos', title:'A few useful details', intro:'These views are optional, but can help show smaller marks.'},
  {key:'damage', title:'Any existing marks?', intro:'Note the scratches, dents, chips or other details you want included.'},
  {key:'review', title:'Review your draft', intro:'Check the details and photos while the vehicle is still with you.'}
];
const photoLabels = Object.fromEntries(steps.slice(2,10).map(s=>[s.key,s.title.replace('Photograph the ','')]));
const draftKey = 'hiw-vehicle-draft-v1';
const app = document.querySelector('#capture-app');
const progressLabel = document.querySelector('#progress-label');
const progressFill = document.querySelector('#progress-fill');
const fresh = () => ({step:0, vehicle:{}, transport:{}, photos:{}, damage:[], updatedAt:null});
let draft;
try { draft = {...fresh(), ...JSON.parse(localStorage.getItem(draftKey) || '{}')}; } catch { draft = fresh(); }
draft.step = Math.max(0, Math.min(steps.length-1, Number(draft.step)||0));
let db;
const urls = [];
function escapeHTML(value=''){return String(value).replace(/[&<>"']/g, char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));}
function save(){draft.updatedAt=new Date().toISOString();localStorage.setItem(draftKey,JSON.stringify(draft));}
function openDB(){return new Promise((resolve,reject)=>{const req=indexedDB.open('howitwas-preview-v1',1);req.onupgradeneeded=()=>req.result.createObjectStore('photos');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});}
function photoAction(mode,key,blob){return new Promise((resolve,reject)=>{const tx=db.transaction('photos',mode==='get'?'readonly':'readwrite');const req=mode==='put'?tx.objectStore('photos').put(blob,key):mode==='delete'?tx.objectStore('photos').delete(key):tx.objectStore('photos').get(key);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});}
function previewURL(blob){const url=URL.createObjectURL(blob);urls.push(url);return url;}
function releaseURLs(){urls.splice(0).forEach(url=>URL.revokeObjectURL(url));}
function field(label,key,value='',required=false,type='text',extra=''){return `<label class="field"><span>${label}${required?' *':''}</span><input name="${key}" type="${type}" value="${escapeHTML(value)}" ${required?'required':''} ${extra}/></label>`;}
function actions(previous=true,next='Continue'){return `<div class="step-actions">${previous?'<button class="button button-light" type="button" data-action="back">← Back</button>':'<span></span>'}<button class="button button-dark" type="submit">${next} <span aria-hidden="true">→</span></button></div>`;}
function error(message=''){const el=app.querySelector('.inline-alert');if(el)el.textContent=message;}
async function render(){
  releaseURLs(); const index=draft.step, step=steps[index];
  progressLabel.textContent=`Step ${index+1} of ${steps.length} · ${step.key==='review'?'Review':index<2?'Details':index<11?'Photos':'Existing marks'}`;
  progressFill.style.width=`${Math.round((index+1)/steps.length*100)}%`;
  let body='';
  if(step.key==='details') body=`<div class="field-grid">${field('Registration','registration',draft.vehicle.registration,true)}${field('Make','make',draft.vehicle.make,true)}${field('Model','model',draft.vehicle.model,true)}${field('Year','year',draft.vehicle.year,false,'number','min="1900" max="2100"')}${field('Colour','colour',draft.vehicle.colour)}${field('VIN (optional)','vin',draft.vehicle.vin)}</div>${actions(false)}`;
  else if(step.key==='transport') body=`<div class="field-grid">${field('Collection date','collectionDate',draft.transport.collectionDate,false,'date')}${field('Transporter','carrier',draft.transport.carrier)}${field('From','origin',draft.transport.origin)}${field('To','destination',draft.transport.destination)}</div>${actions()}`;
  else if(index>=2&&index<=9){const blob=await photoAction('get',step.key);body=`<div class="photo-drop">${blob?`<div><img src="${previewURL(blob)}" alt="Your ${escapeHTML(step.title.toLowerCase())} photo"/><label for="step-photo">Replace photo</label></div>`:`<div><div class="step-icon" aria-hidden="true">◎</div><label for="step-photo">Take or choose a photo</label><p class="photo-hint">One photo for this view · JPEG, PNG or HEIC where supported</p></div>`}<input id="step-photo" type="file" accept="image/*" capture="environment"/></div><div class="inline-alert" role="alert"></div>${actions(true,blob?'Next view':'Save and continue')}`;}
  else if(step.key==='details_photos'){let cards='';for(const [key,label] of [['windscreen','Windscreen'],['wheels','Wheels and tyres'],['roof','Roof'],['odometer','Odometer']]){const blob=await photoAction('get',key);cards+=`<div class="review-card">${blob?`<img src="${previewURL(blob)}" alt="${label}"/>`:`<div class="empty-photo">No photo added</div>`}<strong>${label}</strong><label class="subtle-button" for="detail-${key}">${blob?'Replace':'Add photo'}</label><input id="detail-${key}" type="file" accept="image/*" capture="environment" data-photo-key="${key}" hidden/></div>`;}body=`<div class="review-grid">${cards}</div><div class="field-grid">${field('Odometer reading (km)','odometerKm',draft.vehicle.odometerKm,false,'number','min="0"')}</div><div class="inline-alert" role="alert"></div>${actions()}`;}
  else if(step.key==='damage'){const list=draft.damage.map((d,i)=>`<div class="damage-item"><div><strong>${escapeHTML(d.area)}</strong> · ${escapeHTML(d.kind||'Mark')}<br/><small>${escapeHTML(d.description)}</small>${d.photo?'<br/><small>Photo included</small>':''}</div><button type="button" data-action="remove-damage" data-index="${i}">Remove</button></div>`).join('');body=`<div class="damage-list">${list||'<p>No existing marks added. This does not assert that the vehicle has no damage.</p>'}</div><div class="field-grid">${field('Where is it?','area','',false,'text','placeholder="e.g. Driver door"')}${field('Type of mark','kind','',false,'text','placeholder="e.g. Scratch"')}<label class="field full">Description<textarea name="description" placeholder="Describe its location and appearance"></textarea></label><label class="field full">Close-up photo (optional)<input name="damagePhoto" type="file" accept="image/*" capture="environment"/></label></div><button class="button button-light" type="button" data-action="add-damage">+ Add this mark</button><div class="inline-alert" role="alert"></div>${actions(true,'Review draft')}`;}
  else {const photos=[];for(const [key,label] of Object.entries(photoLabels)){const blob=await photoAction('get',key);photos.push(`<div class="review-card">${blob?`<img src="${previewURL(blob)}" alt="${escapeHTML(label)}"/>`:'<div class="empty-photo">Missing photo</div>'}<strong>${escapeHTML(label)}</strong><span>${blob?'Captured in this draft':'Not captured'}</span></div>`);}body=`<div class="review-head"><strong>${escapeHTML([draft.vehicle.make,draft.vehicle.model].filter(Boolean).join(' ')||'Vehicle')} · ${escapeHTML(draft.vehicle.registration||'No registration')}</strong><p>${escapeHTML(draft.transport.origin||'Origin not entered')} → ${escapeHTML(draft.transport.destination||'Destination not entered')} · ${escapeHTML(draft.transport.collectionDate||'Date not entered')}</p></div><p><strong>${draft.damage.length} existing mark${draft.damage.length===1?'':'s'} noted</strong></p><div class="review-grid">${photos.join('')}</div><div class="notice"><strong>This is a local draft.</strong> It has no verified server timestamp, permanent backup or tamper-evident seal. Keep your original photos separately.</div><div class="step-actions"><button type="button" class="button button-light" data-action="back">← Edit marks</button><button type="button" class="button button-dark" data-action="print">Print draft summary <span aria-hidden="true">↗</span></button></div><p style="margin-top:30px"><button class="subtle-button" type="button" data-action="restart">Delete this draft and start again</button></p>`;}
  app.innerHTML=`<form class="capture-panel" id="capture-form"><span class="section-index">${index<2?'GETTING READY':index<11?'WALK AROUND':index===11?'CONDITION NOTES':'YOUR LOCAL DRAFT'}</span><h2>${step.title}</h2><p>${step.intro}</p>${body}</form>`;
}
async function setPhoto(key,file){if(!file)return;if(!file.type.startsWith('image/')){error('Please select an image file.');return;}if(file.size>12*1024*1024){error('Choose a photo smaller than 12 MB for this preview.');return;}try{await photoAction('put',key,file);draft.photos[key]={name:file.name,size:file.size,type:file.type};save();await render();}catch{error('This device could not save the photo. Check available storage.');}}
app.addEventListener('change',async event=>{const input=event.target;if(input.matches('#step-photo'))await setPhoto(steps[draft.step].key,input.files[0]);else if(input.matches('[data-photo-key]'))await setPhoto(input.dataset.photoKey,input.files[0]);});
app.addEventListener('submit',async event=>{event.preventDefault();const form=event.target;if(!form.reportValidity())return;const key=steps[draft.step].key;if(key==='details'){draft.vehicle={...draft.vehicle,...Object.fromEntries(new FormData(form).entries())};}else if(key==='transport'){draft.transport=Object.fromEntries(new FormData(form).entries());}else if(key==='details_photos'){draft.vehicle.odometerKm=new FormData(form).get('odometerKm')||'';}else if(draft.step>=2&&draft.step<=9){if(!draft.photos[key]){error('Add a photo for this view to continue.');return;}}draft.step=Math.min(steps.length-1,draft.step+1);save();await render();window.scrollTo({top:0,behavior:'smooth'});});
app.addEventListener('click',async event=>{const button=event.target.closest('[data-action]');if(!button)return;const action=button.dataset.action;if(action==='back'){draft.step=Math.max(0,draft.step-1);save();await render();}else if(action==='add-damage'){const form=app.querySelector('form'),data=new FormData(form);const area=String(data.get('area')||'').trim(),description=String(data.get('description')||'').trim();if(!area||!description){error('Add the area and a description first.');return;}const id=crypto.randomUUID(),file=data.get('damagePhoto');if(file instanceof File&&file.size){if(!file.type.startsWith('image/')||file.size>12*1024*1024){error('Choose an image smaller than 12 MB.');return;}await photoAction('put',`damage-${id}`,file);}draft.damage.push({id,area,kind:String(data.get('kind')||'').trim(),description,photo:!!(file instanceof File&&file.size)});save();await render();}else if(action==='remove-damage'){const [removed]=draft.damage.splice(Number(button.dataset.index),1);if(removed?.photo)await photoAction('delete',`damage-${removed.id}`);save();await render();}else if(action==='restart'){if(!confirm('Delete this draft and all its photos from this browser?'))return;const tx=db.transaction('photos','readwrite');tx.objectStore('photos').clear();await new Promise(resolve=>tx.oncomplete=resolve);draft=fresh();save();await render();}else if(action==='print'){window.print();}window.scrollTo({top:0,behavior:'smooth'});});
try{db=await openDB();await render();}catch{app.innerHTML='<div class="honesty-box">This browser cannot save a local draft. Try a regular browser window with device storage enabled.</div>';}
